spring.application.name=MindfulBytes
server.port=8080

# DATABASE CONFIG (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/mindful_bytes_db
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Enable H2 Console (to see data at http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# THYMELEAF CONFIG (Hot reloading for HTML)
spring.thymeleaf.cache=false

# Disable open-in-view for better performance in production
spring.jpa.open-in-view=false

http://localhost:8080